name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install new GCC
        run: sudo apt-get install -y gcc-9

      - name: Print GCC version
        run: gcc --version

      - name: Tests
        run: ./test.sh
