name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Print GCC version
        run: gcc-9 --version

      - name: Tests
        run: |
          sed -i 's/g++/g++-9/g' test.sh 
          ./test.sh
